server:
  port: 8088


spring:
  # spring开发环境配置
  application:
    name: mall-tiny-jpa
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # jpa基本配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 安全路径白名单
secure:
  ignored:
    urls:
      - /
      - /swagger-ui.html
      - /swagger-resources/**
      - /v3/api-docs/**
      - /doc.html
      - /actuator/**
      - /admin/login
      - /admin/register