server:
  port: 8088

spring:
  # spring开发环境配置
  application:
    name: mall-tiny-jpa
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # jpa基本配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    username: admin
    password: admin
    enable: true

# 安全路径白名单
secure:
  ignored:
    urls:
      - /
      - /swagger-ui.html
      - /swagger-ui/
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v3/api-docs/**
      - /actuator/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

# JWT相关配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  # 新版jjwt为了加密安全性，使用HS512算法密钥长度必须在512位以上（64个英文符号）
  secret: kgfkknongabzcenqwzxzqdyuoxylynuutbbkriejnfvywbxymqtbpjkpfuvsutgr
  # JWT的超期限时间(60*60*24*7 -> 一周)
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: 'Bearer '

# 雪花算法id生成器基本参数
snowflake:
  # 终端id
  worker-id: 1
  # 数据中心id
  datacenter-id: 1